def gif (idx):
    gif_dict = {
        1: 'agree',
        2: 'applause',
        3: 'awww',
        4: 'dance',
        5: 'deal with it',
        6: 'do not want',
        7: 'eww',
        8: 'eye roll',
        9: 'facepalm',
        10: 'fist bump',
        11: 'good luck',
        12: 'happy dance',
        13: 'hearts',
        14: 'high five',
        15: 'hug',
        16: 'idk',
        17: 'kiss',
        18: 'micdrop',
        19: 'no',
        20: 'omg',
        21: 'oh snap',
        22: 'ok',
        23: 'oops',
        24: 'please',
        25: 'popcorn',
        26: 'smh',
        27: 'scared',
        28: 'seriously',
        29: 'shocked',
        30: 'shrug',
        31: 'sigh',
        32: 'slow clap',
        33: 'sorry',
        34: 'thank you',
        35: 'thumbs down',
        36: 'thumbs up',
        37: 'want',
        38: 'win',
        39: 'wink',
        40: 'yolo',
        41: 'yawn',
        42: 'yes',
        43: 'you got this'
    }
    return gif_dict[idx]

def emotion(idx):
    emotion_dict = {
        1: 'amusement',
        2: 'excitement',
        3: 'relief',
        4: 'anger',
        5: 'fear',
        6: 'sadness',
        7: 'contempt',
        8: 'guilt',
        9: 'satisfaction',
        10: 'contentment',
        11: 'happiness',
        12: 'shame',
        13: 'disgust',
        14: 'pleasure',
        15: 'surprise',
        16: 'embarassment',
        17: 'pride'
    }
    return emotion_dict[idx]